- name: Duplicate
  color: cfd3d7
- name: Milestone Task
  color: 1D76DB

- name: 'Priority: Critical'
  color: B60205
- name: 'Priority: High'
  color: D93F0B
- name: 'Priority: Medium'
  color: FBCA04
- name: 'Priority: Low'
  color: 0E8A16

- name: 'Status: Accepted'
  color: 0E8A16
- name: 'Status: Completed'
  color: 0E8A16
- name: 'Status: In Progress'
  color: BFDADC
- name: 'Status: On Hold'
  description: Temporarily set aside
  color: FBCA04
- name: 'Status: Rejected'
  description: This will not be worked on
  color: B60205
- name: 'Status: Revision Needed'
  color: B60205
- name: 'Status: ToDo'
  color: 0E8A16

- name: 'Type: Enhancement'
  description: New feature or request
  color: 1D76DB
- name: 'Type: Maintenance'
  color: FBCA04
- name: 'Type: Problem/Bug'
  color: B60205
- name: 'Type: Question'
  color: d876e3
