name: Accepted Issues Automation
on:
  issues:
    types: [labeled]
      
jobs:
  accepted-issues-automation:
    build:
      if: ${{ github.event.label.name == 'Status: Accepted' }}
      runs-on: ubuntu-latest
      steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: 'OSAB General'
          column: 'General'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
