name: Copy Labels
on: workflow_dispatch

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install packages
      run: npm install

    - name: Run build
      run: npm run build:linux

    - name: Moving build to artifacts directory
      run: ./scripts/copylabels.sh
