name: Discord Messages
on: workflow_dispatch

jobs:
 discord-messages:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: readme
      uses: michael2macdonald/discord-message-updater@v1.1
      with:
        discord_token: ${{ secrets.DISCORD_BOT_2_TOKEN }}
        message_file: Discord-Posts/readme.md
        discord_channel: '829005760359825429'
        discord_message: new        
