name: Discord Messages
on: workflow_dispatch

jobs:
 discord-messages:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2.3.4
    - name: readme
      uses: michael2macdonald/discord-message-updater@v1.1.1
      with:
        discord_token: ${{ secrets.DISCORD_BOT_TOKEN }}
        post_file: /github/workspace/Discord-Posts/readme.md
        discord_channel: '829005760359825429' # N.B. The quote marks here are required
        discord_message: '849769031313522731' # Optional, use quotes if specifying an ID. If not supplied, the bot will update the last message in the channel
        
