name: Issues Automation
on:
  issues:
    types: [labeled, assigned]
      
jobs:
  accepted-issues-automation:
    if: "${{ github.event.label.name == 'Status: Accepted' }}"
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: alex-page/github-project-automation-plus@v0.7.1
      with:
        project: OSAB General
        column: General
        repo-token: ${{ secrets.PAT }}
  assigned-issues-automation:
    if: "${{ github.event_name == 'assigned' }}"
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: alex-page/github-project-automation-plus@v0.7.1
      with:
        project: OSAB General
        column: General
        repo-token: ${{ secrets.PAT }}
  not-assigned-issues-automation:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.event_name }}"
    - uses: alex-page/github-project-automation-plus@v0.7.1
      with:
        project: OSAB General
        column: General
        repo-token: ${{ secrets.PAT }}
