name: Stats

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  OrgStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          ACCESS_TOKEN: ${{ secrets.MICHAEL_ACCESS_TOKEN }}
        run: |
          curl "https://api.github.com/orgs/Open-Source-Autonomous-Boat" \
          -H 'authorization: Bearer $ACCESS_TOKEN' \
          -H 'Accept: application/json' \
          | jq '.public_repos .followers .collaborators .public_gists'
      - env:
          ACCESS_TOKEN: ${{ secrets.MICHAEL_ACCESS_TOKEN }}
        run: |
          curl "https://api.github.com/orgs/Open-Source-Autonomous-Boat" \
          -H 'authorization: Bearer $ACCESS_TOKEN' \
          -H 'Accept: application/json' \
          | jq '.public_repos .followers .collaborators .public_gists' > Stats/OrgStats.json
      - run: |
          git diff
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git diff --quiet || (git add -A && git commit -m "Updated with latest")
          git push
  OrgOutsideCollabStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          ACCESS_TOKEN: ${{ secrets.MICHAEL_ACCESS_TOKEN }}
        run: |
          curl "https://api.github.com/orgs/Open-Source-Autonomous-Boat/outside_collaborators" \
          -H 'authorization: Bearer $ACCESS_TOKEN' \
          -H 'Accept: application/json' \
          | jq '.type' > Stats/OrgOutsideCollabStats.json
      - run: |
          git pull
          git diff
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git diff --quiet || (git add -A && git commit -m "Updated with latest")
          git push
          
