name: Stats

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  OrgStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.GITHUB_REPOSITORY_OWNER }}
      - run: |
          curl https://api.github.com/orgs/${{ github.GITHUB_REPOSITORY_OWNER }} \
          -H 'Accept: application/json' \
          | jq '.public_repos .followers .collaborators .public_gists'
      - run: |
          curl https://api.github.com/orgs/${{ github.GITHUB_REPOSITORY_OWNER }} \
          -H 'Accept: application/json' \
          | jq '.public_repos .followers .collaborators .public_gists' > Stats/OrgStats.json
      - run: |
          git diff
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git diff --quiet || (git add -A && git commit -m "Updated with latest")
          git push
  OrgOutsideCollabStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl --request GET \
          --url https://api.github.com/orgs/${{ github.GITHUB_REPOSITORY_OWNER }}/outside_collaborators \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          | jq '.type' > 'Stats/OrgOutsideCollabStats.json'
      - run: |
          git pull
          git diff
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git diff --quiet || (git add -A && git commit -m "Updated with latest")
          git push
          
