name: Sync Labels
on:
  push:
    branches:
      - main
    paths:
      - labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: path/to/manifest/labels.yml
          repository: 
            - Open-Source-Autonomous-Boat/Private
            - Open-Source-Autonomous-Boat/Protoypes
            - Open-Source-Autonomous-Boat/Docs
            - Open-Source-Autonomous-Boat/Miine-Software
            - Open-Source-Autonomous-Boat/Miine-Hardware
            - Open-Source-Autonomous-Boat/Discord-bot
          token: ${{ secrets.PAT }}
