name: Sync Labels
on:
  workflow_dispatch:
    paths:
      - labels.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: Open-Source-Autonomous-Boat/Private
          token: ${{ secrets.PAT }}
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: Open-Source-Autonomous-Boat/Protoypes
          token: ${{ secrets.PAT }}
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: Open-Source-Autonomous-Boat/Docs
          token: ${{ secrets.PAT }}
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: Open-Source-Autonomous-Boat/Miine-Software
          token: ${{ secrets.PAT }}
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: Open-Source-Autonomous-Boat/Miine-Hardware
          token: ${{ secrets.PAT }}
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: Open-Source-Autonomous-Boat/Discord-bot
          token: ${{ secrets.PAT }}





