name: Sync Labels
on: workflow_dispatch

jobs:
  sync:

    strategy:
      fail-fast: false
      matrix:
        repo:
          - Open-Source-Autonomous-Boat/OSAB
          - Open-Source-Autonomous-Boat/Private
          - Open-Source-Autonomous-Boat/Prototypes
          - Open-Source-Autonomous-Boat/Docs
          - Open-Source-Autonomous-Boat/Miine-Software
          - Open-Source-Autonomous-Boat/Miine-Hardware
          - Open-Source-Autonomous-Boat/Discord-bot
          - Open-Source-Autonomous-Boat/GPSTools-Library
          
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Sync
        uses: micnncim/action-label-syncer@v1.2.0
        with:
          manifest: '.github/labels.yml'
          repository: ${{ matrix.repo }}
          token: ${{ secrets.PAT }}





